version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - HOSTNAME=mongodb
    ports:
      - "27017:27017"
    networks: 
      - my-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - HOSTNAME=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - my-net
networks:
  my-net:
    driver: bridge
